[tool.poetry]
name = "python"
version = "1.0"
description = ""
authors = ["Matthew Carruth <carruthm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
